import 'stream-browserify';
import 'react-native-url-polyfill/auto';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { createClient } from '@supabase/supabase-js';
import * as ImagePicker from 'expo-image-picker';
import { StatusBar } from 'expo-status-bar';
import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, Image, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

const supabase=createClient(process.env.EXPO_PUBLIC_SUPABASE_URL??'',process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY??'',{auth:{storage:AsyncStorage,autoRefreshToken:true,persistSession:true,detectSessionInUrl:false}});
type Profile={id:string;nickname:string;avatar_url:string|null};
type Room={id:string;name:string;description:string};
type Message={id:string;user_id:string;nickname:string;body:string;created_at:string;room_id:string|null;conversation_id:string|null};
type Target={kind:'room'|'dm';id:string;title:string;avatar?:string|null};
const C={bg:'#F4F2EB',surface:'#FAF8F2',ink:'#1D1A22',muted:'#797480',line:'#DDD8CD',accent:'#5A43C6',soft:'#E7E2D8',danger:'#A23747'};

function Avatar({profile,size=46}:{profile:Partial<Profile>;size?:number}){return profile.avatar_url?<Image source={{uri:profile.avatar_url}} style={{width:size,height:size,borderRadius:size/2,backgroundColor:C.line}}/>:<View style={{width:size,height:size,borderRadius:size/2,backgroundColor:C.line,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:size/2,fontWeight:'600',color:C.muted}}>?</Text></View>}
export default function App(){
 const [me,setMe]=useState<Profile|null>(null),[uid,setUid]=useState(''),[rooms,setRooms]=useState<Room[]>([]),[people,setPeople]=useState<Profile[]>([]),[messages,setMessages]=useState<Message[]>([]),[target,setTarget]=useState<Target|null>(null),[draft,setDraft]=useState(''),[nick,setNick]=useState(''),[tab,setTab]=useState<'rooms'|'people'|'settings'>('rooms'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{void boot();return()=>{void supabase.removeAllChannels()}},[]);
 async function boot(){const {data:{session}}=await supabase.auth.getSession();let user=session?.user;if(!user){const r=await supabase.auth.signInAnonymously();user=r.data.user??undefined;if(r.error){setError('Не удалось подключиться');setLoading(false);return}}setUid(user.id);const {data}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!data){const n='Аноним'+Math.random().toString().slice(-4);await supabase.from('profiles').insert({id:user.id,nickname:n});setMe({id:user.id,nickname:n,avatar_url:null});setNick(n)}else{setMe(data);setNick(data.nickname)}await Promise.all([refreshRooms(),refreshPeople(user.id)]);supabase.channel('profiles').on('postgres_changes',{event:'*',schema:'public',table:'profiles'},(e)=>{if(e.eventType==='INSERT'||e.eventType==='UPDATE'){const p=e.new as Profile;setPeople(l=>l.find(x=>x.id===p.id)?l.map(x=>x.id===p.id?p:x):[...l,p])}else if(e.eventType==='DELETE'){setPeople(l=>l.filter(x=>x.id!==(e.old as any).id))}}).subscribe();supabase.channel('rooms').on('postgres_changes',{event:'*',schema:'public',table:'rooms'},(e)=>{if(e.eventType==='INSERT'){setRooms(l=>[...l,e.new as Room])}else if(e.eventType==='UPDATE'){setRooms(l=>l.map(x=>x.id===(e.new as Room).id?e.new as Room:x))}else if(e.eventType==='DELETE'){setRooms(l=>l.filter(x=>x.id!==(e.old as any).id))}}).subscribe();supabase.channel('messages').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},(e)=>{const m=e.new as Message;if(target&&((target.kind==='room'&&m.room_id===target.id)||(target.kind==='dm'&&m.conversation_id===target.id))){setMessages(l=>[...l,m])}}).subscribe();setLoading(false)};
 async function refreshRooms(){const r=await supabase.from('rooms').select('*').order('name');setRooms(r.data??[])}
 async function refreshPeople(id=uid){const r=await supabase.from('profiles').select('*').neq('id',id).order('nickname');setPeople(r.data?? [])}
 async function saveProfile(){const clean=nick.trim().replace(/\s+/g,' ').slice(0,24);if(clean.length<2){setError('Ник минимум 2 символа');return}const r=await supabase.from('profiles').update({nickname:clean}).eq('id',uid);if(r.error){setError('Не удалось сохранить');return}setMe(me?{...me,nickname:clean}:null);setError('')}
 async function chooseAvatar(){const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted){setError('Разреши доступ к фотографиям');return}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,allowsEditing:true,aspect:[1,1],quality:0.8});if(!r.canceled){const img=r.assets[0];const ext=img.uri.split('.').pop()??'jpg';const path=`${uid}-${Date.now()}.${ext}`;const file=await fetch(img.uri).then(x=>x.blob());const {error}=await supabase.storage.from('avatars').upload(path,file,{upsert:true});if(error){setError('Не удалось загрузить');return}const {data}=supabase.storage.from('avatars').getPublicUrl(path);const u=await supabase.from('profiles').update({avatar_url:data.publicUrl}).eq('id',uid);if(u.error){setError('Не удалось обновить профиль');return}setMe(me?{...me,avatar_url:data.publicUrl}:null)}}
 async function open(t:Target){setTarget(t);const q=supabase.from('messages').select('*').order('created_at',{ascending:true}).limit(300);const r=t.kind==='room'?await q.eq('room_id',t.id):await q.eq('conversation_id',t.id);setMessages(r.data?? [])}
 async function dm(p:Profile){const r=await supabase.rpc('start_dm',{target:p.id});if(r.error){setError('Не удалось открыть личный чат');return}await open({kind:'dm',id:r.data,title:p.nickname,avatar:p.avatar_url})}
 async function send(){const body=draft.trim().slice(0,1000);if(!body||!target||!me)return;setDraft('');const row:any={user_id:uid,nickname:me.nickname,body,room_id:null,conversation_id:null};row[target.kind==='room'?'room_id':'conversation_id']=target.id;const r=await supabase.from('messages').insert(row);if(r.error){setError('Ошибка отправки');setDraft(body)}}
 if(loading)return <SafeAreaView style={s.center}><ActivityIndicator color={C.accent}/><Text style={s.muted}>Подключаемся…</Text></SafeAreaView>;
 if(!me)return <SafeAreaView style={s.onboard}><StatusBar style="dark"/><Text style={s.logo}>ТЧ</Text><View><Text style={s.kicker}>АНОНИМНОЕ ОБЩЕНИЕ</Text><Text style={s.hero}>Клавиатура</Text></View></SafeAreaView>;
 if(target)return <SafeAreaView style={s.page}><StatusBar style="dark"/><View style={s.chatHead}><Pressable onPress={()=>setTarget(null)} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.chatTitle}>{target.title}</Text></View><Avatar profile={{avatar_url:target.avatar??null}}/></View><FlatList data={messages} keyExtractor={m=>m.id} renderItem={({item:m})=><View style={[s.msg,m.user_id===uid?s.own:s.other]}><Text style={s.msgAuthor}>{m.nickname}</Text><Text style={s.msgBody}>{m.body}</Text></View>} contentContainerStyle={s.msgList}/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.input}><TextInput value={draft} onChangeText={setDraft} placeholder="Сообщение…" placeholderTextColor={C.muted} style={s.field} multiline/><Pressable onPress={send} style={s.send}><Text style={s.sendText}>›</Text></Pressable></KeyboardAvoidingView></SafeAreaView>;
 return <SafeAreaView style={s.page}><StatusBar style="dark"/><View style={s.top}><View><Text style={s.kicker}>{tab==='rooms'?'ОБЩЕНИЕ':tab==='people'?'ЛЮДИ':'НАСТРОЙКИ'}</Text><Text style={s.title}>{tab==='rooms'?'Комнаты':tab==='people'?'Люди':'Профиль'}</Text></View><Avatar profile={me} size={56}/></View>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text><Pressable onPress={()=>setError('')}><Text style={s.errorClose}>✕</Text></Pressable></View>:null}{tab==='rooms'?<FlatList data={rooms} keyExtractor={r=>r.id} renderItem={({item:r})=><Pressable onPress={()=>open({kind:'room',id:r.id,title:r.name})} style={s.item}><Text style={s.itemTitle}>{r.name}</Text><Text style={s.itemDesc}>{r.description}</Text></Pressable>} contentContainerStyle={s.list}/>:tab==='people'?<FlatList data={people} keyExtractor={p=>p.id} renderItem={({item:p})=><Pressable onPress={()=>dm(p)} style={s.item}><View style={s.itemFlex}><Avatar profile={p}/><View style={s.itemText}><Text style={s.itemTitle}>{p.nickname}</Text></View></View></Pressable>} contentContainerStyle={s.list}/>:<ScrollView contentContainerStyle={s.settings}><Text style={s.settingsLabel}>Ник</Text><TextInput value={nick} onChangeText={setNick} style={s.field} maxLength={24}/><Pressable onPress={saveProfile} style={s.btn}><Text style={s.btnText}>Сохранить</Text></Pressable><Pressable onPress={chooseAvatar} style={[s.btn,{backgroundColor:C.soft}]}><Text style={s.btnText}>Аватар</Text></Pressable></ScrollView>}<View style={s.nav}><Pressable onPress={()=>setTab('rooms')} style={[s.navBtn,tab==='rooms'&&s.navActive]}><Text style={s.navIcon}>💬</Text></Pressable><Pressable onPress={()=>setTab('people')} style={[s.navBtn,tab==='people'&&s.navActive]}><Text style={s.navIcon}>👤</Text></Pressable><Pressable onPress={()=>setTab('settings')} style={[s.navBtn,tab==='settings'&&s.navActive]}><Text style={s.navIcon}>⚙</Text></Pressable></View></SafeAreaView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,backgroundColor:C.bg},onboard:{flex:1,padding:24,justifyContent:'space-around',backgroundColor:C.bg},logo:{fontSize:48,fontWeight:'900',color:C.accent,textAlign:'center'},kicker:{fontSize:12,fontWeight:'600',color:C.muted,textTransform:'uppercase'},title:{fontSize:28,fontWeight:'700',color:C.ink},hero:{fontSize:32,fontWeight:'700',color:C.ink},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:16,borderBottomWidth:1,borderBottomColor:C.line},chatHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingHorizontal:16,paddingVertical:12,borderBottomWidth:1,borderBottomColor:C.line,gap:12},chatTitle:{fontSize:18,fontWeight:'600',color:C.ink},back:{padding:8},backText:{fontSize:24,color:C.ink},list:{padding:16,gap:8},item:{padding:16,backgroundColor:C.surface,borderRadius:8,marginBottom:8},itemFlex:{flexDirection:'row',gap:12,alignItems:'center'},itemText:{flex:1},itemTitle:{fontSize:14,fontWeight:'600',color:C.ink},itemDesc:{fontSize:12,color:C.muted,marginTop:4},msgList:{padding:16,gap:12},msg:{padding:12,borderRadius:8,maxWidth:'85%'},own:{backgroundColor:C.accent,alignSelf:'flex-end'},other:{backgroundColor:C.surface,alignSelf:'flex-start'},msgAuthor:{fontSize:11,fontWeight:'600',color:C.muted,marginBottom:4},msgBody:{fontSize:14,color:C.ink},input:{flexDirection:'row',padding:16,gap:12,borderTopWidth:1,borderTopColor:C.line},field:{flex:1,backgroundColor:C.surface,borderRadius:8,paddingHorizontal:12,paddingVertical:8,fontSize:14,color:C.ink,maxHeight:100},send:{width:40,height:40,backgroundColor:C.accent,borderRadius:8,alignItems:'center',justifyContent:'center'},sendText:{fontSize:20,color:'white',fontWeight:'bold'},error:{backgroundColor:'#FEE2E2',borderBottomWidth:1,borderBottomColor:'#FECACA',padding:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},errorText:{color:'#991B1B',flex:1,fontSize:12},errorClose:{color:'#991B1B',fontSize:18,fontWeight:'bold'},settings:{padding:16,gap:16},settingsLabel:{fontSize:12,fontWeight:'600',color:C.muted,textTransform:'uppercase'},btn:{backgroundColor:C.accent,padding:12,borderRadius:8,alignItems:'center'},btnText:{color:'white',fontWeight:'600',fontSize:14},nav:{flexDirection:'row',justifyContent:'space-around',borderTopWidth:1,borderTopColor:C.line,paddingVertical:8,backgroundColor:C.surface},navBtn:{paddingVertical:8,paddingHorizontal:16},navIcon:{fontSize:20},navActive:{borderBottomWidth:2,borderBottomColor:C.accent},muted:{color:C.muted,fontSize:12}});
